# How many warp shards are required for the warp to be made
# This amount of shards will be removed from the players inventory
# Warp shards are an exact match - renaming, adding enchants etc will prevent them from working
createWarpCost: 10

# Number of warp shards required to move a warp
moveWarpCost: 5

# Number of warp shards required to rename a warp
renameWarpCost: 5

# Number of warp shards required to make an inactive warp active
reactivateWarpCost: 10

# The name of the item that displays the warp
# Use %warp% for the warp name
warpName: "&r&6%warp%"

# The name of the item that displays the inactive warp
# Use %warp$ for the warp name
inactiveWarpName: "&r&c%warp% &8(inactive)"

# Amount of days to pass for a warp to be marked as 'inactive'
# Inactive warps cannot be teleported to unless the user has a permission to teleport to them
inactiveDays: 30

# Featured Warp Algorithm
# The 'ranking' of warps is calculated through the factors listed below. Changing the weighting below changes
# how much of an affect it has on the 'ranking' - the higher the weight, the greater the effect.
# Weights either positively or negatively affect the ranking. Positive weights increase the ranking, negative decrease
# If you wish to flip the effect of a weighting, make the weighting negative
# Weights can also be set to 0 to make their value have no effect
# Formula:
# Ranking = uniqueHits * weighting + weeklyVisitorAverage * weighting - warpUptime * weighting - ownerDowntime * weighting

# How many unique players have visited the warp. This value positively affects ranking
uniqueHitsWeighting: 1

# An average of how many unique players visit this warp every week. This value positively affects ranking
weeklyVisitorAverageWeighting: 0

# How long the warp has been around in days. This value negatively affects ranking
warpUptimeWeighting: 1

# How long it has been since the owner of the warp has been online in days. This value negatively affects ranking
ownerDowntimeWeighting: 1


# A linear formula for the number of warps an island can have
prestigePerWarp: 10

# The maximum number of warps an island can have, regardless of the formula above
# Use 0 to leave it uncapped
maximumWarps: 5


# A list of all categories players can set their warps to. No limit on how many categories you create
# Each category requires a name and attached to that name a material, which is then displayed to the users
# Examples
# categories:
#   Grinder: BONE
#   Shop: EMERALD
#   Nether: NETHERRACK
#   Build: BRICK
#   default: STONE
categories:
  Grinder: BONE
  Shop: EMERALD
  Nether: NETHERRACK
  Build: BRICK
  default: STONE

# The default category whenever a warp is created
# Note that it must also be in the list above
defaultCategory: "default"

# Worlds the player can create warps in
# Modifying this list will require a server restart and will not work with /pwa reload
# You will have to include the default worlds in this list if you want players to create warps in them
# please note that these names MUST be correct, as there is no check if the world is not valid
# Example
# worlds:
#   - "world"
#   - "world_nether"
worlds:
  - "Skyblock"





