name: "PrimeWarps"
main: me.Scyy.PrimeWarps.Plugin
version: ${project.version}
api-version: 1.16
author: "Scyphers"
softdepend:
  - Skyblock
  - Multiverse-Core
commands:
  pwarp:
    description: "Provides the GUI and easy access to teleporting to player-made warps"
    aliases: ["pw", "playerwarp"]
  pwadmin:
    description: "Provides admin tools for managing player warps"
    aliases: ["pwa", "playerwarpadmin"]
  warprequest:
    description: "Used to request the creation of a warp. Server admins have to approve a warp before it becomes live"
    aliases: ["wrequest"]